### ISSUE TITLE
How to reduce queries?

### ISSUE THREAD

**Issue by kiogo** [calebporzio/onboard#12]
Implemented per instructions, and it works great, however I'm getting a huge jump in the number of queries - specifically the number of duplicated queries.

For example, on my dashboard I had 7 queries, 2 duplicated. After adding 8 Onboarding steps I have 28queries, 23 duplicated.

Any idea why the high number of duplicate queries?

**Comment by calebporzio** [comment]
I'm not exactly sure. Maybe post your Onboarding config from your service provider? Maybe you are accessing something in there?

Maybe try installing https://github.com/barryvdh/laravel-debugbar to learn more about those queries and where they came from if you aren't doing this already.

**Comment by adddz** [comment]
Loop into this as I just realized I'm experiencing the same issue.

Excerpt of the Onboarding config:

 ```
Onboard::addStep('Visit Page')
    ->link('/app/page')
    ->cta('Visit Page')
    ->completeIf(function (User $user) {
        return $user->pageViews()->wherePath($path)->count();
    });
```

Obviously, the culprit is the query I'm executing. Any ideas on how to improve this without having to make that query every single time (multiplied by the time that `complete()` is called)?

**Comment by Jamesking56** [comment]
@adddz Maybe cache the result of `$user->pageViews()->wherePath($path)->count()` in that closure?
