### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by petersuhm** [calebporzio/onboard#13]
Are there any plans to support Laravel 5.8? I'm wondering if it requires anything besides adding it to the composer.json file or if the package actually needs to be updated?

**Comment by calebporzio** [comment]
Probably just needs the composer.json addition. mind pring?

**Comment by petersuhm** [comment]
Done https://github.com/calebporzio/onboard/pull/14

**Comment by calebporzio** [comment]
Thanks!

**Comment by oluwajubelo1** [comment]
@petersuhm , unable to install this package for laravel 5.8.

**Comment by oluwajubelo1** [comment]
Thanks, i've been able to install. It was actually a network issue.
