### ISSUE TITLE
Class 'App\Providers\Onboard' not found

### ISSUE THREAD

**Issue by fsuuaas** [calebporzio/onboard#15]
Got Fatal Error when adding 
```
	    Onboard::addStep('Complete Profile')
	    	->link('/profile')
	    	->cta('Complete')
	    	->completeIf(function (User $user) {
	    		return $user->profile->isComplete();
	    	});
```
in App\Providers\AppServiceProvider.php

**Comment by PovilasKorop** [comment]
@fsuuaas I bumped into the same error, and made it work by referencing different class. Suggested README changes in this Pull Request: https://github.com/calebporzio/onboard/pull/17
