### ISSUE TITLE
Possible to have an end-to-end working example that uses  calebporzio/onboard?

### ISSUE THREAD

**Issue by connecteev** [calebporzio/onboard#16]
@calebporzio thank you for this package and the work you're doing for Laravel. I've been looking for a good package to add an onboarding flow to my app, and this is the only one out there.

Would it be possible for you to put out an end-to-end (simple) working example? It would help me and others that are stuck with the instructions.

**Comment by connecteev** [comment]
Just spent 2 hours but couldn't figure out how to make this package work

**Comment by oluwajubelo1** [comment]
@connecteev , kindly check out this tutorial on youtube: https://www.youtube.com/watch?v=PFPpwsb1pBY

**Comment by connecteev** [comment]
@oluwajubelo1 I did see that, thanks

**Comment by oluwajubelo1** [comment]
You're welcome @connecteev
