### ISSUE TITLE
Support Laravel 5.7.*

### ISSUE THREAD

**Issue by usamaejaz** [calebporzio/onboard#7]
As the title suggests, the installation fails for laravel 5.7.*. Migration of 5.6 to 5.7 has only a few changes required. It may not even require any change for this package though I am not sure.

**Comment by usamaejaz** [comment]
I created this pull request as I needed this to be fixed quickly for me. https://github.com/calebporzio/onboard/pull/8

**Comment by calebporzio** [comment]
Thanks for the PR!
